server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;


    location ~ ^/(banking-service|identification-service|investment-service|notification-service|audit-admin-service)/ {
    proxy_pass http://gateway:8080;
}

    location / {
        try_files $uri $uri/ /index.html;
    }
}